---
title: "Symbiont density analysis"
author: "HM Putnam, AS Huffmyer"
edited by: "DM Becker-Polinski"
date: "20220310"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

# Import data
```{r}
# Cell count data
sym_counts <- read_csv("timepoint2/2_data/2_sym_counts/2_symbiont_counts.csv")

# Surface area data
sa <- read.csv("timepoint2/2_output/2_surface.area.calc.csv")

# Tissue homogenate volume data
homog_vols <- read_csv("timepoint2/2_data/2_homogenate_vols/2_homogenate_vols.csv") %>% select(1:3)

# Coral sample metadata
metadata <- read_csv("timepoint2/2_metadata.csv") %>% select(1:4)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vols) %>%
  full_join(sa)
```

# Calculate cells per square centimeter
```{r}
# Calculate mean counts for each sample
sym_counts <- sym_counts %>%
  select(fragment_ID, Squares.Counted, matches("Count[0-9]")) %>%
  gather("rep", "count", -fragment_ID, -Squares.Counted) %>%
  group_by(fragment_ID, Squares.Counted) %>%
  summarise(mean_count = mean(count, na.rm = TRUE))

# Join mean counts with sample metadata
sym_counts <- full_join(sym_counts, metadata)

# Normalize counts by homogenat volume and surface area
sym_counts <- sym_counts %>%
  mutate(cells.mL = mean_count * 10000 / Squares.Counted,
         cells = cells.mL * homogenate_vol_ml,
         cells.cm2 = cells / surface.area.cm2)
```


# Plot data
```{r}
sym_counts %>%
  #filter(!is.na(site)) %>%
  ggplot(aes(x = timepoint, y = cells.cm2 / 10^6, color = timepoint)) +
  labs(x = "") +
  ylab(expression(bold(paste(atop("Cell Density", "(" *x*"10"^"6" *~cells *~ cm^"-2"*")"))))) + #using quotations over numbers allow them to be bold
  #facet_wrap(~ species) +
geom_jitter(width = 0.1) +                                            # Plot all points
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.5) +
  stat_summary(fun.y = mean, geom = "point", color = "black")           # Plot mean
```


Output data to file.  

```{r}
sym_counts %>%
  select(fragment_ID, timepoint, cells.cm2) %>%
  mutate(timepoint="TP2")%>%
  write_csv(path = "timepoint2/2_output/2_sym_densities.csv")


```
